name: FOSSA scanning

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2025-12-17T23%3A01%3A41.484000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
    timeout-minutes: 40
