name: Label PR
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  labeler:
    name: Add component labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2025-12-17T23%3A01%3A41.484000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v6
      - uses: actions/labeler@v6
        with:
          configuration-path: .github/component-label-map.yml
    timeout-minutes: 40
