name: Lint

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2025-12-17T23%3A01%3A41.484000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: npm
      - run: npm ci --ignore-scripts
      - name: Compile
        run: npm run compile
      - name: Lint
        run: |
          npm run lint
    timeout-minutes: 40
